language: julia
os:
    - linux
julia:
    - release
notifications:
    email: false
env:
    matrix:
        - PKGADD="JSON" JULIAVERSION="juliareleases"
        - PKGADD="JSON" JULIAVERSION="julianightlies"
after_success:
    - julia -e 'cd(Pkg.dir("JSON")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
